# Dockerfile for the DASH project
FROM          ubuntu:latest

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y
RUN           apt-get install -y \
                  git \
                  build-essential \
                  cmake \
                  libhwloc-plugins \
                  libhwloc-dev

# Install PAPI from source
WORKDIR       /tmp

# Compiler error when compiling with -pedantic for papi > 5.4.1
# ADD         http://icl.utk.edu/projects/papi/downloads/papi-5.5.1.tar.gz papi.tgz
ADD           http://icl.cs.utk.edu/projects/papi/downloads/papi-5.4.1.tar.gz papi.tgz
RUN           tar -xf papi.tgz
RUN           cd papi*/src/                     \
              && ./configure --prefix=/opt/papi \
              && make                           \
              && make install
# Openmpi 2.0
ADD           https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.gz ompi.tgz
RUN           tar -xf ompi.tgz
RUN           cd openmpi*                           \
              && ./configure --prefix=/opt/openmpi  \
              && make                               \
              && make install
# Prepare env
ENV           PAPI_BASE=/opt/papi
ENV           LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PAPI_BASE}/lib:/opt/openmpi/lib
ENV           PATH=${PATH}:/opt/openmpi/bin
ENV           MPI_EXEC_FLAGS='--allow-run-as-root'
ENV           VERBOSE_CI='true'
# Workaround for issue #63
ENV           GTEST_FILTER="-SharedTest.AtomicAdd:TransformTest.Array*:CopyTest.AsyncLocalToGlobPtr"

# Set workdir to dash home
WORKDIR       /opt/dash
