# Dockerfile for the DASH project
FROM          ubuntu:latest

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y
RUN           apt-get install -y \
                  git \
                  build-essential \
                  cmake \
                  libhwloc-plugins \
                  libhwloc-dev \
                  libmpich-dev \
                  libhdf5-mpich-dev

# Install PAPI from source
WORKDIR       /tmp

ADD           http://icl.utk.edu/projects/papi/downloads/papi-5.5.1.tar.gz papi.tgz
RUN           tar -xf papi.tgz
RUN           cd papi*/src/                     \
              && ./configure --prefix=/opt/papi \
              && make                           \
              && make install
ENV           PAPI_BASE=/opt/papi
ENV           LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PAPI_BASE}/lib
ENV           VERBOSE_CI='true'

# Set workdir to dash home
WORKDIR       /opt/dash
