# Dockerfile for the DASH project
FROM          ubuntu:latest

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y
RUN           apt-get install -y \
                  git \
                  build-essential \
                  cmake \
                  libhwloc-plugins \
                  libhwloc-dev \
                  libopenmpi-dev \
                  openmpi-bin \
                  openmpi-common \
                  libhdf5-openmpi-dev

# Install PAPI from source
WORKDIR       /tmp

# Compiler error when compiling with -pedantic for papi > 5.4.1
# ADD         http://icl.utk.edu/projects/papi/downloads/papi-5.5.1.tar.gz papi.tgz
ADD           http://icl.cs.utk.edu/projects/papi/downloads/papi-5.4.1.tar.gz papi.tgz
RUN           tar -xf papi.tgz
RUN           cd papi*/src/                     \
              && ./configure --prefix=/opt/papi \
              && make                           \
              && make install
ENV           PAPI_BASE=/opt/papi
ENV           LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PAPI_BASE}/lib
ENV           MPI_EXEC_FLAGS='--allow-run-as-root'
ENV           VERBOSE_CI='true'

# Set workdir to dash home
WORKDIR       /opt/dash
