#ifndef DASH__ALGORITHM__GENERATE_N_H__
#define DASH__ALGORITHM__GENERATE_N_H__

#include <dash/Array.h>
#include <dash/iterator/GlobIter.h>
#include <dash/algorithm/LocalRange.h>
#include <dash/algorithm/Operation.h>
#include <dash/dart/if/dart_communication.h>

namespace dash {

/**
 * Assigns values, generated by given function object g, 
 * to the first count elements in the range beginning
 * at first, if count>0. Does nothing otherwise.
 * 
 * \ingroup DashAlgorithms
 *
 */ 

template<
 typename ElementType,
 class    PatternType,
 class    Size,
 class    Generator>
void generate_n( 
 GlobIter<ElementType, PatternType> first,
 Size                               count,
 Generator g) {

   /***********************************************************
    *  To-do: 
    *  This is a sequential implemenation
    *  of generate_n. Implement generate_n by using local_range.
    *  Is there a possiblity to use dash::localrange(first)
    *  without second ("last") parameter?
    ***********************************************************/

   for (Size i = 0; i < count; i++) {
   
     *first++ = g();

   } 
   return first;

}


}


#endif // DASH__ALGORITHM__GENERATE_N_H__
