
all : supermuc-hw


supermuc-hw :
#	./template.pl NNODES=5,CLASS=micro     supermuc-hw.ll > supermuc-hw-5.job
#	./template.pl NNODES=10,CLASS=micro    supermuc-hw.ll > supermuc-hw-10.job
#	./template.pl NNODES=15,CLASS=micro    supermuc-hw.ll > supermuc-hw-15.job
#	./template.pl NNODES=20,CLASS=micro    supermuc-hw.ll > supermuc-hw-20.job
	./template.pl NNODES=25,CLASS=general  supermuc-hw.ll > supermuc-hw-25.job
	./template.pl NNODES=30,CLASS=general  supermuc-hw.ll > supermuc-hw-30.job
	./template.pl NNODES=35,CLASS=general  supermuc-hw.ll > supermuc-hw-35.job
	./template.pl NNODES=40,CLASS=general  supermuc-hw.ll > supermuc-hw-40.job
	./template.pl NNODES=45,CLASS=general  supermuc-hw.ll > supermuc-hw-45.job
	./template.pl NNODES=50,CLASS=general  supermuc-hw.ll > supermuc-hw-50.job
	./template.pl NNODES=55,CLASS=general  supermuc-hw.ll > supermuc-hw-55.job
	./template.pl NNODES=60,CLASS=general  supermuc-hw.ll > supermuc-hw-60.job
	./template.pl NNODES=60,CLASS=general  supermuc-hw.ll > supermuc-hw-60.job
	./template.pl NNODES=70,CLASS=general  supermuc-hw.ll > supermuc-hw-70.job
	./template.pl NNODES=80,CLASS=general  supermuc-hw.ll > supermuc-hw-80.job
	./template.pl NNODES=90,CLASS=general  supermuc-hw.ll > supermuc-hw-90.job
	./template.pl NNODES=100,CLASS=general supermuc-hw.ll > supermuc-hw-100.job

clean :
	rm -f *~
	rm -f *.job
