# Dockerfile for the DASH project
# This container is based on the openmpi2 container
# and pre configured for valgrind tests
# do NOT use this container for anything else

FROM          ubuntu:latest 

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y --fix-missing
RUN           apt-get install -y \
                git \
                build-essential \
                cmake \
                uuid-runtime \
                libhwloc-plugins \
                libhwloc-dev \
                libc6-dbg

WORKDIR       /tmp

# Build valgrind from source
ADD           http://valgrind.org/downloads/valgrind-3.12.0.tar.bz2 vg.tar.bz2
RUN           tar -xf vg.tar.bz2
RUN           cd valgrind-3*                        \
              && ./configure --prefix=/opt/valgrind \
              && make                               \
              && make install
ENV           VALGRIND_BASE=/opt/valgrind
ENV           PATH=${PATH}:${VALGRIND_BASE}/bin

# Openmpi 2.0
ADD           https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.2.tar.gz ompi.tgz
RUN           tar -xf ompi.tgz
RUN           cd openmpi*                                     \
              && ./configure --prefix=/opt/openmpi            \
                             --enable-debug                   \
                             --enable-memchecker              \
                             --with-valgrind=${VALGRIND_BASE} \
              && make                                         \
              && make install

# Prepare env
ENV           EXEC_PREFIX="LD_PRELOAD=${VALGRIND_BASE}/lib/valgrind/libmpiwrap-amd64-linux.so"
ENV           EXEC_WRAP="valgrind --track-origins=yes --leak-check=full"

# temporary disable hanging tests
ENV           GTEST_FILTER="-SharedTest.AtomicAdd:TransformTest.Array*:CopyTest.AsyncLocalToGlobPtr"

# Set workdir to dash home
WORKDIR       /opt/dash
