# Dockerfile for the DASH project
FROM          ubuntu:latest

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y
RUN           apt-get install -y cmake libhwloc-plugins libhwloc-dev \
                          git build-essential valgrind valgrind-mpi

# Install PAPI 5.5.0 from source
WORKDIR       /tmp

# Latest version of PAPI is not compatible
# ADD           http://icl.cs.utk.edu/projects/papi/downloads/papi-5.5.0.tar.gz papi.tgz

ADD           http://icl.cs.utk.edu/projects/papi/downloads/papi-5.4.1.tar.gz papi.tgz
RUN           tar -xf papi.tgz
RUN           cd papi*/src/                                  \
              && ./configure --prefix=/opt/papi --with-ffsll \
              && make                                        \
              && make install
# Openmpi 2.0
ADD           https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.gz ompi.tgz
RUN           tar -xf ompi.tgz
RUN           cd openmpi*                           \
              && ./configure --prefix=/opt/openmpi  \
              && make                               \
              && make install
# Prepare env
ENV           PAPI_BASE=/opt/papi
ENV           LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PAPI_BASE}/lib:/opt/openmpi/lib
ENV           PATH=${PATH}:/opt/openmpi/bin
ENV           MPI_EXEC_FLAGS='--allow-run-as-root --map-by core'
ENV           VERBOSE_CI='true'
ENV           EXEC_WRAP="valgrind --track-origins=yes --leak-check=full"

# Set workdir to dash home
WORKDIR       /opt/dash
