# Dockerfile for the DASH project
FROM          dashproject/ci:openmpi2

MAINTAINER    The DASH Team <team@dash-project.org>

RUN           apt-get update -y
RUN           apt-get install libc6-dbg

# Build valgrind from source
WORKDIR       /tmp
ADD           http://valgrind.org/downloads/valgrind-3.12.0.tar.bz2 vg.tar.bz2
RUN           tar -xf vg.tar.bz2
RUN           cd valgrind-3*                        \
              && ./configure --prefix=/opt/valgrind \
              && make                               \
              && make install

# Prepare env
ENV           PATH=${PATH}:/opt/valgrind/bin
ENV           EXEC_WRAP="valgrind --track-origins=yes --leak-check=full"

# Set workdir to dash home
WORKDIR       /opt/dash
